version: '3.8'
services:
  nexapod-server:
    restart: always
    image: ghcr.io/darkstarstrix/nexapod-server:latest
    ports:
      - "8000:8000"
    volumes:
      - ./Server/config.yaml:/app/config.yaml:ro

  nexapod-client:
    restart: always
    image: ghcr.io/darkstarstrix/nexapod-client:latest
    depends_on:
      - nexapod-server
    environment:
      COORDINATOR_URL: "http://nexapod-server:8000"
    volumes:
      - ~/.nexapod:/root/.nexapod

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./Infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
