FROM python:3.11-slim
ENV APP_USER=nexapod
RUN addgroup --system $APP_USER && adduser --system --ingroup $APP_USER $APP_USER
WORKDIR /app

# Copy requirements first to leverage Docker layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY ./Infrastructure /app/Infrastructure
COPY ./Server /app/Server

USER $APP_USER
EXPOSE 8000
CMD ["python", "-m", "Server.app"]
