name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t nexapod-server:latest -f Infrastruture/Dockerfile.server .
          docker build -t nexapod-client:latest -f Infrastruture/Dockerfile.client .

      - name: Run containers
        run: |
          docker run -d --name nexapod-server -p 8000:8000 nexapod-server:latest
          docker run -d --name nexapod-client -p 8501:8501 nexapod-client:latest

      - name: Check container status
        run: |
          docker ps
          sleep 10
          docker logs nexapod-server
          docker logs nexapod-client
